wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.10
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.7
    start_time: 1644318967
    t:
      1:
      - 1
      4: 3.9.7
      5: 0.12.10
      8:
      - 4
      - 5
data_dict:
  desc: null
  value:
    names:
    - mask
    nc: 1
    test: /Users/victorgaya/Documents/Cours/M2/computer_vision/FaceMaskRecognition/data/test/images
    train: /Users/victorgaya/Documents/Cours/M2/computer_vision/FaceMaskRecognition/data/train/images
    val: /Users/victorgaya/Documents/Cours/M2/computer_vision/FaceMaskRecognition/data/valid/images
